
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCiEAkHqNFTkQ4aQuo_wmLrDhW-ojE_b1E",
      authDomain: "flutterproject-45152.firebaseapp.com",
      projectId: "flutterproject-45152",
      storageBucket: "flutterproject-45152.appspot.com",
      messagingSenderId: "955677204934",
      appId: "1:955677204934:web:af80760b19c52ee62f52c7"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMHGzADkfoWOZk7DLMVnmRVQGWjLAJ5Mk',
    appId: '1:955677204934:android:b04f71f332ed5e122f52c7',
    messagingSenderId: '955677204934',
    projectId: 'flutterproject-45152',
    storageBucket: 'flutterproject-45152.appspot.com',
  );
}
